kubeutils/kube_cfg.go
this is being used currently in an upcoming PR for `glooctl` which wants to read the default kube namespace from the kubeconfig (so the user doesn't have to manuall provide it)
=> add helper for retrieving the kube config itself

changelog/v0.2.10/release-asset-cli.yaml, cloudbuild.yaml, docsutils/cli.go, githubutils/README.md, githubutils/upload_release_asset.go, versionutils/cli.go
Migrating repositories to `UploadReleaseAssetCli`, distributed in `go-utils/githubutils/cli.go`. 
Convention changes:
* With the `SkipAlreadyExists: true` flag, this script will not error if some / all of the artifacts were already uploaded (does simplistic checking on name only). This enables re-running release builds without needing to clear state, when a release build fails. 
* Use this CLI instead of shell script. Script will be removed from repos. 
* Move away from `release` target, create `upload-github-release-assets` make target instead. 
* Target is always run, logic to determine if this is a release is in the CLI. Make target should be: 
```.PHONY: upload-github-release-assets
upload-github-release-assets:
go run upload_github_release_assets.go
```
This assumes the release …
=> Upload release asset cli

changelog/v0.2.11/fix-sha-to-match-shasum.yaml, githubutils/upload_release_asset.go
Now use hex encoding to produce a string, and format like:
`<hex of sha256> <file basename>\n`
=> Fix shasum

changelog/v0.7.9/package-manager-update.yaml, pkgmgmtutils/update_formula_test.go, pkgmgmtutils/update_formulas.go
Allows FormulaOptions.Name to be a descriptive name for logging, and
FormulaOptions.FormulaName used for proper formula name as needed for
branch and commit naming conventions required for external PRs.
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/128
=> Added pkgmgmtutils.FormulaOptions.FormulaName field

changelog/v0.9.18/install.yaml, testutils/helper/install.go
https://github.com/kubernetes/kubernetes/issues/66689
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/259
=> Wait for default service acct to avoid race

changelog/v0.10.7/improve-toml-parsing.yaml, versionutils/repo.go, versionutils/repo_test.go
Consider all possible version fields (`version`, `branch`, `revision`) when retrieving a dependency version from a .toml file.
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/291
=> Get dependency version from revision/branch fields

changelog/v0.10.25/manifest-filter.yaml, manifesttestutils/util.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/337
=> Allow selecting the resources from the helm manifest to assert against

changelog/v0.10.26/logrus.yaml, changelog/v0.10.27/logrus.yaml, go.mod, go.sum
After this, I can pull in go-utils as long as I use this replace in my downstream projects: 
`replace github.com/Sirupsen/logrus => github.com/sirupsen/logrus v1.0.6`
And I also make sure I don't pull in a package of Sirupsen as an indirect dependency. 
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/340
=> Update logrus take 1

changelog/v0.14.1/fix-github-500-retry-logic.yaml, githubutils/upload_release_asset.go
Open and close the file within the retry loop so that if the github client closes it after an HTTP 500 failure, when we retry, the file is open before we attempt upload.
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/394
=> Ensure release asset file is open before attempting upload in retry loop

changelog/v0.16.5/stats-log-level.yaml, stats/stats.go
Add a new `LogLevel` startup option to inject the `zap.AtomicLevel` into the stats server. This way clients can build their own logger and use the stats server to change its log level at runtime, instead of having to rely on the logger built internally by the server.
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/413
=> Add a new `LogLevel` startup option to the stats server

changelog/v0.20.5/add-log-level-changing-via-env-var.yaml, stats/stats.go
This PR updates the stats server so that the log level can be set by the environment variable that is present on start. My plan is to add this environment variable into the Helm templates so that it can be configured by the values overrides.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4090
=> Set level with environment variable

changelog/v0.21.0/fix-homebrew-formula-regex.yaml, healthchecker/grpc.go, healthchecker/grpc_test.go
The grpc health checker used to default to serving. We should allow the client to inject the initial serving status. This PR enables that.
=> Grpc health checker supports default value

changelog/v0.21.2/add-custom-order-tag-label.yaml, changelogutils/changelog_test.go, changelogutils/validator.go, changelogutils/validator_test.go, versionutils/version.go, versionutils/version_test.go
Adds `labelOrder` to changelogValidator. If `labelOrder` exists, then changelogValidator
will now use the order specified in this array to tie-break tags with same versions but different labels.
e.g. if e.g. labelOrder = [ beta, alpha, predev ], then 1.7.0-beta11 > 1.7.0-alpha5 > 1.7.0-predev9.
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/441
=> Custom tag comparator

changelog/v0.21.3/fix-fail-handler.yaml, testutils/fail_handler.go
Examples are from running [these tests](https://github.com/solo-io/solo-projects/blob/34cd83404ab0a8f320ec83dbc6fa3d8e19d315d3/install/test/helm_suite_test.go#L38).
Before this change:
After this change:
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/443
=> Fix line reporting in fail handler

.github/workflows/pull_request.yaml
Per https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions the default condition is `success()` which doesn't run if previous steps failed. This means that job failures weren't getting uploaded to testspace. This fixes that.
=> Always run testspace, even on failures

changelog/v0.21.5/log-level-fix.yaml, stats/stats.go
When setting the stat server log level via an environment variable. previously the log config was not being built so logs would not be produced. This also prevented logs from being produced when set via the admin api after the server started without a log config. This fix builds the log config so that the log level is applied and logs are produced.
Tested this locally with a gloo image that pulled in this change and a defined the env var.
=> Build logger when an env var is set

changelog/v0.21.9/fix-docs-gen-ratelimit-issue.yaml, githubutils/repo.go
Github API Paginations starts at page 1: https://docs.github.com/en/rest/guides/traversing-with-pagination#navigating-through-the-pages. We should start querying at page 1 so we don't get duplicate results for page 0 and page 1.
=> Fix github api pagination

.github/workflows/pull_request.yaml, changelog/v0.21.11/security-scan-create-github-issue.yaml, githubutils/repo.go, githubutils/repo_test.go, osutils/executils/exec.go, securityscanutils/README.md, securityscanutils/securityscan.go, securityscanutils/trivy_templates.go
Adds option to Security Scanner to create github issues for each image that a vulnerability is found in.
If an issue already exists for that image, it will update the issue with the most recent vulnerability scan results. 
This is especially useful for reporting vulnerabilities in private repositories, because the "Code scanning results" tab for private repositories is a paid-feature.
Example generated issue: https://github.com/solo-io/solo-projects/issues/2467
=> Create vulnerability Github Issues on Trivy scan

changelog/v0.21.16/trivy-retries.yaml, githubutils/repo.go, securityscanutils/securityscan.go
- Introduce a RepositoryReleasesPredicate, allowing clients to define the filter behavior for github repository releases. Ideally, we could configure this in the API request, but unfortunately that is not supported at the moment.
- Add retries to our Trivy scanning logic. We noticed a flake in a previous run: https://github.com/solo-io/gloo/runs/3280618311?check_suite_focus=true, that we hope will be resolved by adding some retries, though we are not sure.
=> Support Trivy Scan Retries

changelog/v0.21.19/deprecate-exponentioal-backoff.yaml, contextutils/backoff.go
Reviewers should confirm that this is not a breaking change before approving.
=> Deprecate backoff functions with typo

changelog/v0.21.22/avoid-empty-gh-issue.yaml, securityscanutils/securityscan.go
When the security scanner finds no vulnerabilities for a version, it still creates a github issue:
https://github.com/solo-io/solo-projects/issues/2790
Do not create an issue if it is empty.
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/2739
=> Do not create empty Github issues on trivy scans with no vulnerabilities

changelog/v0.21.26/bump-crypto-dep.yaml, securityscanutils/securityscan.go
Make sec gen less noisy and faster
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/478
=> securityscanutils: Only scan the latest patch version for a given minor release

changelog/v0.21.27/fix-stats-logging-npe.yaml, contextutils/context_and_logging.go, stats/runtime.go, stats/stats.go, stats/stats_suite_test.go, stats/stats_test.go, testutils/goimpl/curl.go
Ensure that the stats server can handle requests to the `/logging` endpoint
The logging endpoint is a useful feature for debugging components. In fact, we even recommend this feature in our production debugging docs for Gloo Edge: https://docs.solo.io/gloo-edge/latest/operations/debugging_gloo/#changing-logging-levels-and-more
This feature has been broken for a while. You can see the [history](https://github.com/solo-io/go-utils/commits/master/stats/stats.go), but it has changed enough and been broken in different ways, that I decided to add a robust set of tests around the functionality.
In its most recent state, this handler is nil every time, unless the StartupOptions define a custom LogLevel.
I introduced a context aspect to this server, to ensure that we can shutdown the server when …
=> Fix NPE in Stats Server Logging Handler

.github/workflows/pull_request.yaml, changelog/v0.21.27/trivy-github-issue-per-minor.yaml, githubutils/repo.go, securityscanutils/github_writer.go, securityscanutils/predicate.go, securityscanutils/predicate_test.go, securityscanutils/securityscan.go, securityscanutils/trivy_scanner.go, stats/stats.go, stats/stats_test.go
- Fix bug in Trivy scanner which caused the scan to only run on the latest patch version
- Expose new flag that allows Github issues to be created only for the latest patch version, as opposed to all versions
In https://github.com/solo-io/go-utils/issues/478, we identified that our historical scan implementation would create a Github issue for every version scanned that contained a vulnerability, and that this was extremely noisy to developers.
As a result, we added a slight adjustment to the code in https://github.com/solo-io/go-utils/pull/479. The unintended side effect of this was in addition to only creating github issues only for the latest patch release, we also only scanned the latest patch release. This speeds up our weekly job tremendously, but it also no longer produces results …
=> Trivy Scanning: Scan all images and only create issue for latest patch release

changelog/v0.22.3/configurable-changelog-dir.yaml, changelogutils/changelog.go, changelogutils/reader.go, changelogutils/reader_test.go, changelogutils/validator.go, changelogutils/validator_test.go
This should enable users to have less sprawling changelog directorys as time progresses.  Consider a directory like...
```yaml
changelog:
v1.0.0
v1.0.1
v1.0.2
v1.1.0
v1.1.1
v1.1.2
v1.1.3
```
By specifying a activeSubdirectory="v1.1", you could achieve a more readable structure of
```yaml
changelog:
v1.0:
v1.0.0
v1.0.1
v1.0.2
v1.1
v1.1.0
v1.1.1
v1.1.2
v1.1.3
```
=> feat(changelogutils): added `activeSubdirectory` field to "validation.yaml"

.github/workflows/pull_request.yaml, changelog/v0.24.1/new-benchmark-util.yaml, testutils/benchmarking/benchmarking.go
This PR adds the `Measure` function to the `benchmarking` test utility package. The new function measures the portion of time a given test function spent in user mode, in kernel mode, and in both of them combined. The other functions in the same package have been deprecated and will be removed when other repositories will stop depending on them.
The change was prompted by the fact that the current `TimeForFuncToComplete` function is in some instances reporting execution times of 0 nanoseconds, which causes failures in benchmark tests. I had encountered this problem [before](https://github.com/solo-io/ext-auth-service/pull/425#issuecomment-1276678054) and decided to spend some time to investigate it this time around as it seemed to be manifesting itself increasingly often during [my …
=> New benchmark function

changelog/v0.24.2/fix-test-utils-double-import.yaml, testutils/exec/cmd.go
Removed double-importing of "github.com/pkg/errors" and the import of the non-v2 "github.com/onsi/ginkgo"
Faced an error in solo-project's [CI](https://console.cloud.google.com/cloud-build/builds/98233170-52e0-4aa2-bdd3-05adb9d4b478?project=gloo-ee) due to the `v0.24.1` update.
```
Step #0 - "tests": Step #12 - "test": # github.com/solo-io/go-utils/testutils/exec
Step #0 - "tests": Step #12 - "test": /go/pkg/mod/github.com/solo-io/go-utils@v0.24.1/testutils/exec/cmd.go:13:2: ginkgo redeclared in this block
Step #0 - "tests": Step #12 - "test": 	/go/pkg/mod/github.com/solo-io/go-utils@v0.24.1/testutils/exec/cmd.go:10:2: other declaration of ginkgo
Step #0 - "tests": Step #12 - "test": /go/pkg/mod/github.com/solo-io/go-utils@v0.24.1/testutils/exec/cmd.go:13:2: "github.com/onsi/ginkgo/v2" …
```
=> Fix testutils double import issue

changelog/v0.24.7/mapstructure-utils.yaml, go.mod, go.sum, mapstructureutils/mapdecoder.go, mapstructureutils/mapdecoder_suite_test.go, mapstructureutils/mapdecoder_test.go
Normalizes and decodes map interfaces that can have (deeply nested) numbers of type json.Number
by setting those to either to int64 or float64.
Usually, you don't need to normalize a map[string]interface{}, that you are decoding into a struct with mapstructure
Unless,, you will use it with `structpb.NewValue()` which doesn't handle that type and throws an invalid type error.
=> mapstructuredecoder that produces structpb safe output

changelog/v0.25.1/13898-formatting-missing-images.yaml, securityscanutils/securityscan.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo-mesh-enterprise/issues/13898
Diff of generated Markdown.
The issue mentions a few images missing from the 2.4.7 report which are now included after these changes.
=> [13898] Fix formatting; Explicitly state no vulnerabilities

changelog/v0.27.1/fix-alpine-labeling.yaml, changeloggenutils/merged_release.go
The way this utility is generating the json for the changelog used by our documentation portal results in duplicate entries when the release label is "alpine". This PR sets the LabelVersion value to 1 when it detects a label of "alpine". This results in a unique version for the alpine build and the non-alpine build.
I'm open to other ways of solving this, but there cannot be duplicate version keys in the resulting json.
Before:
```json
{
"v1.16.11": {
"Categories": {
"Dependency Bumps": [
{
"Note": "solo-io/gloo has been upgraded to v1.16.16."
}
],
"Fixes": [
{
"Note": "Fix an issue where the wrong query param was discovered for a rest resolver. (https://github.com/solo-io/solo-projects/issues/6275)"
},
{
"Note": "Fixing MaxDepth not processed and propagated to envoy. …
```
=> Coerce LabelVersion to 1 for alpine labels

changelog/v0.27.2/enable-pre-release-scan.yaml, securityscanutils/commands/format_results.go, securityscanutils/commands/scan_repo.go, securityscanutils/commands/utils.go, securityscanutils/predicate.go, securityscanutils/predicate_test.go, securityscanutils/securityscan.go
Conditionally allows running image scans against Github releases marked as pre-release.
Testing done:
- Unit test
- Manual test
without `--enable-pre-release`
```
$ go run /src/code/go-utils/securityscanutils/cli scan-repo -v     -i /src/code/gloo-operator/docs/cmd/imageVersionConstraints.csv    -c ">=v0.1.0-0"         -r us-docker.pkg.dev/solo-public/gloo-operator  -g gloo-operator        -a output-locally          -d /src/code/gloo-operator/docs/cmd/securityScanDebugInstructions.md
{"level":"debug","ts":"2024-11-21T13:12:11.845-0800","caller":"securityscanutils/securityscan.go:176","msg":"Number of github releases to scan: 0"}
```
with `--enable-pre-release`
```
go run /src/code/go-utils/securityscanutils/cli scan-repo -v     -i …
```
=> security-scan: conditionally allow scanning pre-release versions

changelog/v0.28.4/fixing-cache-issue.yaml
I was seeing issues with mismatch checksums with v0.28.0. While debugging, I made tags and used them in another repo, likely tainting the sum cache. The other versions worked as expected. This PR steps over the likely tainted sums.
=> Stepping over cache issue

changelog/v0.28.5/update-gh-issue-writer.yaml, securityscanutils/issuewriter/github_writer.go
When trivy scan runs and creates/updates GH issue it resets labels to ('trivy', 'vulnerability'). This leads to labels getting purged which gets added manually e.g 'Prioritized' label added by product
related issue : https://github.com/solo-io/gloo-mesh-enterprise/issues/20331
This PR updates security scan gh issue writer to merge labels instead of overriding them.
test GH issue : https://github.com/solo-io/gloo-mesh-enterprise/issues/20604
test run using this PR branch which respects existing labels
```
go get github.com/solo-io/go-utils@rav/gh-issue-writer-update
GOPRIVATE=github.com/solo-io GO111MODULE=on go run github.com/solo-io/go-utils/securityscanutils/cli scan-repo -v \
-i ./docs/cmd/imageVersionConstraints.csv \
-c "=v2.4.16" \
-r gcr.io/gloo-mesh \
-g gloo-mesh-enterprise \
-a …
```
=> don't reset labels when updating gh issue for trivy scan

changelog/v0.28.6/go-1-24-6.yaml, go.mod
Update Go version to 1.24.6
snyk errors can be ignored as those scans are in the process of being implemented.
=> Update Go version to 1.24.6
