solo-io/go-utils

- testutils/kubernetes.go
needed for some knative tests where connections can take up to 30s to start
> put connection timeout behind an option in curl helper

- changelogutils/changelog.go
- changelogutils/changelog_test.go
- changelogutils/cli.go
- changelogutils/markdown.go
- docsutils/cli.go
- githubutils/repo.go
> Changelog cli

- changelog/v0.2.9/clidoc1.yaml
- clidoc/README.md
- clidoc/docgen.go
Now that our cli-to-online-docs pipeline is stabilizing, let's reuse this code
> extract common clidoc gen logic

- changelog/v0.6.3/quiet-curl.yaml
- testutils/helper/curl.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/91
> add verbosity flags to curl utils

- changelog/v0.7.2/add-utils.yaml
- kubeutils/util.go
- versionutils/cli.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/108
resolves https://github.com/solo-io/go-utils/issues/99
> More utils

- changelog/v0.7.3/listing-cached-values.yaml
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
- installutils/kubeinstall/mocks/mock_kube_installer.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/110
> List cached values for a label key

- changelog/v0.7.4/listing-cached-values.yaml
- installutils/kubeinstall/installer_callbacks.go
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/113
> Propagate resource deletion

- changelog/v0.7.5/retry-kubeinstaller-opts.yaml
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/117
> add opts to kube installer

- changelog/v0.7.6/fix-cache-access.yaml
- installutils/kubeinstall/kube_installer.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/119
> Fix cache access

- changelog/v0.7.7/github-manifest.yaml
- fsutils/afero.go
- installutils/helmchart/manifests.go
- installutils/helmchart/manifests_test.go
- vfsutils/afero.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/121
resolves https://github.com/solo-io/go-utils/issues/122
> Helm from GitHub

- changelog/v0.7.10/cliutils.yaml
- surveyutils/input.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/130
> add GetDurationInput GetFloat32Input to SurveyUtils

- changelog/v0.7.11/package-manager-update.yaml
- pkgmgmtutils/update_formula_test.go
- pkgmgmtutils/update_formulas.go
- pkgmgmtutils/utils.go
- pkgmgmtutils/utils_test.go
Also added additional tests, and added additional error checking
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/132
> Parameterized how UpdateFormulas finds sha256 files in build directory

- changelog/v0.7.12/supergloo-version.yaml
- versionutils/repo.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/136
> add supergloo repo to versionutils

- changelog/v0.7.16/repo-init-changlog-v0.yaml
- changelogutils/changelog.go
- githubutils/githubutils_test.go
- githubutils/repo.go
- versionutils/version.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/142
> update changlog validation for v0.0.1 support

- README.md
- changelog/v0.7.18/manifest-test-utils.yaml
- manifesttestutils/README.md
- manifesttestutils/resource_builder.go
- manifesttestutils/test/example.yaml
- manifesttestutils/test/example_suite_test.go
- manifesttestutils/test/example_test.go
- manifesttestutils/util.go
- testutils/make.go
- versionutils/repo.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/146
> Manifest testing utilities

- changelog/v0.7.20/fixes.yaml
- installutils/kubeinstall/kube_installer.go
- manifesttestutils/resource_builder.go
- manifesttestutils/test/example.yaml
- manifesttestutils/test/example_test.go
- testutils/make.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/152
resolves https://github.com/solo-io/go-utils/issues/151
> Various fixes

- changelog/v0.8.1/http-echo-test-pod.yaml
- testutils/helper/http_echo.go
- testutils/helper/test_container.go
- testutils/helper/testrunner.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/157
> http-echo container

- changelog/v0.8.4/test-helper-interface.yaml
- cloudbuild.yaml
- installutils/kubeinstall/kube_installer_test.go
- testutils/helper/curl.go
- testutils/helper/http_echo.go
- testutils/helper/install.go
- testutils/helper/test_container.go
- testutils/helper/test_container_test.go
- testutils/helper/testrunner.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/161
> test helper interface

- changelog/v0.8.6/retrieve-archive.yaml
- installutils/helmchart/manifests.go
- installutils/helmchart/manifests_test.go
- tarutils/main.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/169
> Retrieve archive

- changelog/v0.8.7/expect-configmap-with-yaml-data.yaml
- manifesttestutils/test/example.yaml
- manifesttestutils/test/example_test.go
- manifesttestutils/util.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/171
> expect configmap with yaml data

- changelog/v0.8.8/updates.yaml
- installutils/kuberesource/get_cluster_resources.go
- installutils/kuberesource/unstructured.go
- manifesttestutils/resource_builder.go
- manifesttestutils/util.go
- versionutils/repo.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/175
resolves https://github.com/solo-io/go-utils/issues/174
resolves https://github.com/solo-io/go-utils/issues/165
> secret tests, toml parsing for overrides, and reduced logging

- changelog/v0.8.9/manifest-test.yaml
- manifesttestutils/resource_builder.go
- manifesttestutils/test/example.yaml
- manifesttestutils/test/example_test.go
- manifesttestutils/util.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/178
> fixed and udpated tests

- changelog/v0.8.10/set-log-level.yaml
- contextutils/context_and_logging.go
- versionutils/repo.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/180
resolves https://github.com/solo-io/go-utils/issues/164
> Set log level and improved support for Toml version parsing

- changelog/v0.8.12/termination-log.yaml
- changelogutils/changelog.go
- changelogutils/changelog_test.go
- kubeutils/pod_termination.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/185
resolves https://github.com/solo-io/solobot/issues/100
> termination-logs utils

- changelog/v0.8.13/proto-unmarshal-allow-unknown.yaml
- protoutils/marshal.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/188
> Allow unknown

- changelog/v0.8.14/fix-kube-caching.yaml
- installutils/kubeinstall/kube_installer.go
BOT NOTES: 
resolves https://github.com/solo-io/sm-marketplace/issues/452
> Fix cache staleness

- changelog/v0.8.17/curl-util.yaml
- testutils/goimpl/curl.go
- testutils/goimpl/curl_test.go
- testutils/goimpl/goimpl_suite_test.go
- testutils/trimmed_stack_fail_handler.go
BOT NOTES: 
resolves https://github.com/solo-io/glooshot/issues/16
> introduce go-impl curl util

- changelog/v0.8.18/update_formula.yaml
- pkgmgmtutils/update_formulas.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/719
> Updated formula commit message

- changelog/v0.8.19/manifests-from-resource.yaml
- go.mod
- installutils/helmchart/manifests.go
- installutils/helmchart/manifests_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/196
> Add util function to convert resources to manifest

- changelog/v0.8.20/fix-sort.yaml
- installutils/helmchart/manifests.go
- installutils/helmchart/manifests_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/198
> fix sort on manifests created from resources

- changelog/v0.8.22/fixlogline.yaml
- installutils/kubeinstall/kube_installer.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/209
> simplify logline

- changelog/v0.9.5/sanitize_name_v2.yaml
- kubeutils/util.go
- kubeutils/util_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/232
> changelog and single quotes

- botutils/consts.go
- botutils/hookhandler.go
- botutils/interface.go
- botutils/registry.go
- changelog/v0.9.7/issues.yaml
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/237
> Issues events

- botutils/botconfig/config.go
- botutils/botconfig/os_mock_test.go
- changelog/v0.9.7/gcloudutils.yaml
- changelogutils/mounted_repo_mock_test.go
- changelogutils/repo_client_mock_test.go
- debugutils/mocks_kube_test.go
- debugutils/mocks_test.go
- docsutils/cli.go
- gcloudutils/README.md
- gcloudutils/clients.go
- gcloudutils/cloudbuild_suite_test.go
- gcloudutils/cloudbuild_test.go
- gcloudutils/cloudsub.go
- gcloudutils/factory.go
- gcloudutils/interface.go
- gcloudutils/tags.go
- gcloudutils/types.go
- githubutils/branch.go
- githubutils/commitutils/branch.go
- githubutils/repo_client.go
- go.mod
- randutils/rand.go
- versionutils/version.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/205
> utils for writing bots that do gcloud stuff

- changelog/v0.9.9/fix-issues.yaml
- githubutils/commitutils/branch.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/241
> Fix set ref

- changelog/v0.9.12/expect-proto-with-message.yaml
- testutils/assertions.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/249
> add optional desc to ExpectEqualProtoMessages

- changelog/v0.9.15/wait-for-jobs.yaml
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/254
> update kubeinstaller to wait for jobs to complete

- changelog/v0.9.19/nomad-install.yaml
- hack/increment_semver.sh
- hack/make-changelog-entry.sh
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
- kubeerrutils/kube_errs.go
- testutils/clusterlock/cluster_lock_client.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/pull/263
> make kubeinstaller more robust for creating resources

- changelog/v0.10.0/namespace-override-fix.yaml
- changelog/v0.9.21/namespace-override-fix.yaml
- debugutils/test/debugutils_e2e_suite_test.go
- installutils/kubeinstall/kube_installer.go
- installutils/kubeinstall/kube_installer_test.go
- installutils/kubeinstall/mocks/mock_kube_installer.go
- kubeerrutils/kube_errs.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/pull/266
> Respect manifest namespace

- certutils/certutils_suite_test.go
- certutils/gen_cert.go
- certutils/gen_cert_test.go
- changelog/v0.10.5/gencert.yaml
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/pull/287
> add util to generate certs

- changelog/v0.10.6/pr-tag.yaml
- gcloudutils/builders/context.go
- gcloudutils/builders/gcloud.go
- gcloudutils/tags.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/289
> Support pr tag

- changelog/v0.10.9/crd-manifest-utils.yaml
- manifesttestutils/test/example_test.go
- manifesttestutils/util.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/294
> expect unstructured

- botutils/registry.go
- changelog/v0.10.11/fix-log.yaml
These seem to cause bots to crash
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/301
> Remove log field

- botutils/registry.go
- changelog/v0.10.12/fix-logging.yaml
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/302
> Remove log2

- changelog/v0.10.13/fix.yaml
- githubutils/repo_client.go
- githubutils/repo_client_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/304
> Fix get sha

- changelog/v0.10.14/add-gateway-enterprise-install-constant.yaml
- testutils/helper/install.go
for use by glooctl test helper
> Add gateway enterprise install command

- changelog/v0.10.16/changelog-docs-from-dir.yaml
- changelogutils/changelog.go
- changelogutils/changelog_test.go
- changelogutils/cmd/Makefile
- changelogutils/cmd/README.md
- changelogutils/cmd/main.go
- changelogutils/markdown.go
- vfsutils/mount.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/309
> changelog docs gen from dir

- botutils/hookhandler.go
- botutils/registry.go
- changelog/v0.10.17/logging.yaml
- gcloudutils/clients.go
- gcloudutils/cloudsub.go
- gcloudutils/factory.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/312
> Reduce log verbosity

- changelog/v0.10.22/helm-upgrade.yaml
- changelogutils/README.md
- changelogutils/entrytype.go
- changelogutils/markdown.go
- changelogutils/reader_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/332
> Upgrade and helm cl

- changelog/v0.10.22/changelog-validation.yaml
- changelog/v0.10.23/changelog-validation.yaml
- changelogutils/repo_client_mock_test.go
- changelogutils/validator.go
- changelogutils/validator_test.go
- githubutils/repo_client.go
- githubutils/repo_client_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/331
> start a fix for non-master releases and changelog validation

- changelog/v0.11.1/release-versioning.yaml
- changelogutils/validator.go
- changelogutils/validator_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/353
resolves https://github.com/solo-io/go-utils/issues/352
> Updates to support release model

- changelog/v0.11.4/fix-file-validation.yaml
- changelogutils/validator.go
- changelogutils/validator_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/357
> Validation fix

- changelog/v0.11.5/dry-stats.yaml
- stats/stats.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/363
> DRY out stats server startup config

- changelog/v0.11.8/extract-function.yaml
- changelogutils/validator.go
- changelogutils/validator_test.go
- githubutils/repo_client_test.go
BOT NOTES: 
resolves Expose logic to read validation settings in a public function.
> Extract function

- changelog/v0.13.1/fix-comments-on-exported-functions.yaml
- versionutils/version.go
- versionutils/version_test.go
Fix comments on `MustIsGreaterThan` and `MustIsGreaterThanOrEqualTo` functions
> Fix comments

- changelog/v0.13.2/git-describe-always.yaml
- versionutils/git/version.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/381
> Move to git describe with --always flag

- changelog/v0.13.2/network-util.yaml
- networkutils/ingress.go
This is a clean port of a util that currently lives in 3 other repos. 
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/383
> Port util here

- changelog/v0.13.3/grpc-logging.yaml
- contextutils/errors_and_logging.go
- loggingutils/grpc.go
- loggingutils/grpc_test.go
- loggingutils/loggingutils_suite_test.go
this will allow us to see debug log in ext auth
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/387
> add WithExistingLogger

- changelog/v0.13.3/helminstall.yaml
- changelog/v0.13.4/helminstall-output-formatting.yaml
- installutils/helminstall/installer.go
- loggingutils/grpc.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/385
> Helminstall output fix

- changelog/v0.14.0/helm_kubecontext.yaml
- installutils/helminstall/client.go
- installutils/helminstall/client_test.go
- installutils/helminstall/helm_loaders.go
- installutils/helminstall/installer.go
- installutils/helminstall/installer_test.go
- installutils/helminstall/mocks/mock_helm_client.go
- installutils/helminstall/mocks/mock_helm_loaders.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/392
> Add kube context to helm installer

- changelog/v0.14.2/healthcheck-interceptor.yaml
- contextutils/backoff.go
- healthchecker/grpc.go
- healthchecker/interceptor_test.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2489
> add grpc unary server health check interceptor

- changelog/v0.16.2/sni-curl.yaml
- testutils/helper/curl.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/410
> sni and self-signed

- changelog/v0.16.3/fix-formula-updater.yaml
- pkgmgmtutils/formula_updater.go
- pkgmgmtutils/formula_updater_test.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3178
> Fix version strings used while updating formula

- changelog/v0.16.4/fix-sha256-regex.yaml
- pkgmgmtutils/formula_updater.go
- pkgmgmtutils/formula_updater_test.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3178
> Fix sha256 regex

- changelog/v0.18.1/cliutils-port-forward.yaml
- cliutils/port_forward.go
I'm using it in meshctl, and this function is super useful!
> Add useful PortForwardGet to cliutils

- changelog/v0.19.0/fix-grpc-health.yaml
- healthchecker/grpc.go
- healthchecker/grpc_test.go
- healthchecker/interceptor_test.go
- healthchecker/interface.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/425
> fix grpc health

- changelog/v0.20.3/add-benchmarking-util.yaml
- healthchecker/grpc_test.go
- testutils/benchmarking/benchmarking.go
- testutils/vault.go
Add benchmarking util for testing user time spent in tests.
> Add benchmarking utils

- changelog/v0.20.5/fix-homebrew-formula-regex.yaml
- githubutils/repo.go
- pkgmgmtutils/formula_updater.go
- pkgmgmtutils/formula_updater_test.go
- pkgmgmtutils/internal/formula_bytes_updater_test.go
Empty commits were getting generated in homebrew-core by Solo-io Bot because of incorrect regex parsing and change in homebrew-core.
https://github.com/solo-io/gloo/issues/4047
> Fix homebrew formula tests

- changelog/v0.22.4/require-label.yaml
- changelogutils/validator.go
- changelogutils/validator_test.go
BOT NOTES: 
resolves https://github.com/solo-io/go-utils/issues/503
> Add validation for changelog label

- .github/workflows/codeformat.yaml
- .github/workflows/pull_request.yaml
- changelog/v0.24.1/remove-actions-cache.yaml
See https://github.com/solo-io/gloo/pull/8062#issue-1656108774
> Remove actions/cache

- .github/workflows/pull_request.yaml
- changelog/v0.27.2/expose-morechangelogstuff.yaml
- changeloggenutils/merged_release.go
- changeloggenutils/minor_release.go
- securityscanutils/securityscan_test.go
midterm update post gloo donation
this also forced a trivy upgrade to the same style used else where.
This pr does 3 things.
- Updates release versions to use for tests to fix inconsistent releases in gloo
- Updates trivy to use the same process as other repos and follow best practices
- Exposes new options for users of changelog functionality and unblock https://github.com/solo-io/gloo/pull/10389
> changelog utility for merging stuff

- changelog/v0.27.3/expose-morechangelogstuff.yaml
- changeloggenutils/merged_release.go
extra verbostiy was problematic
see https://github.com/solo-io/docs/blame/4a378de8c291e368ec8af92361edad15a33510ce/static/changelog/glooe-changelog.docgen
> changeloggnenutils: dont be so verbose
